"""Pairing QR cameras for the WWebJS API integration."""

from __future__ import annotations

import logging

from homeassistant.components.camera import Camera
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from . import WWebJSApiConfigEntry
from .api import WWebJSApiError
from .entity import WWebJSSessionEntity

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: WWebJSApiConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up pairing QR cameras for known and newly discovered sessions."""
    coordinator = entry.runtime_data
    known_sessions: set[str] = set()

    @callback
    def async_add_new_sessions() -> None:
        """Add QR cameras for sessions discovered after setup."""
        new_sessions = set(coordinator.data) - known_sessions
        if not new_sessions:
            return
        known_sessions.update(new_sessions)
        async_add_entities(
            [
                WWebJSSessionQrCamera(coordinator, entry, session_id)
                for session_id in sorted(new_sessions)
            ]
        )

    async_add_new_sessions()
    entry.async_on_unload(coordinator.async_add_listener(async_add_new_sessions))


class WWebJSSessionQrCamera(WWebJSSessionEntity, Camera):
    """Camera entity exposing the current WhatsApp pairing QR code."""

    _attr_translation_key = "pairing_qr"
    _attr_icon = "mdi:qrcode"
    _attr_content_type = "image/png"

    def __init__(self, coordinator, entry: ConfigEntry, session_id: str) -> None:
        """Initialize a pairing QR camera."""
        super().__init__(coordinator, entry, session_id)
        self._attr_unique_id = f"{entry.entry_id}_{session_id}_pairing_qr"

    async def async_camera_image(
        self, width: int | None = None, height: int | None = None
    ) -> bytes | None:
        """Return the live QR PNG generated by the WWebJS API."""
        if not self.available:
            return None

        try:
            return await self.coordinator.client.async_get_qr_image(self.session_id)
        except WWebJSApiError as err:
            if err.code == "invalid_auth":
                self._entry.async_start_reauth(self.hass)
            else:
                _LOGGER.debug(
                    "Unable to fetch pairing QR for session %s: %s",
                    self.session_id,
                    err.code,
                )
            return None
